
// Generated by https://quicktype.io

class Metro {
  String situacao;
  String modificado;
  String criado;
  int codigo;
  int id;

  Metro({
    this.situacao,
    this.modificado,
    this.criado,
    this.codigo,
    this.id,
  });

  factory Metro.fromJson(Map<String, dynamic> json){
    return new Metro(
      situacao: json['situacao'],
      modificado: json['modificado'],
      criado: json['criado'],
      codigo: json['codigo'],
      id: json['id']
    );
  }

  
}

class MetroList {
  final List<Metro> metros;

  MetroList({
    this.metros,
  });

  factory MetroList.fromJson(List<dynamic> parsedJson) {

    List<Metro> metros = new List<Metro>();
    metros = parsedJson.map((i)=>Metro.fromJson(i)).toList();

    return new MetroList(
      metros: metros
    );
  }
}

